.\" Copyright (c) 2007 Hyogeol Lee <hyogeollee@gmail.com>
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer
.\"    in this position and unchanged.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHORS ``AS IS'' AND ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
.\" OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
.\" IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
.\" INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
.\" NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
.\" DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
.\" THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
.\" THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
.\"
.Dd March 29, 2007
.Os [FreeBSD] [7.0]
.Dt nm 1
.Sh NAME
.Nm nm
.Nd "Display symbolic information in file."
.Sh SYNOPSIS
.Nm
.Op Fl A | -print-file-name
.Op Fl a | -debug-syms
.Op Fl BP
.Op Fl C | -demangle=style | -no-demangle
.Op Fl D | -dynamic
.Op Fl eg
.Op Fl h | -help
.Op Fl l | -line-numbers
.Op Fl n | -numeric-sort
.Op Fl ox
.Op Fl p | -no-sort
.Op Fl r | -reverse-sort
.Op Fl S | -print-size
.Op Fl s | -print-armap
.Op Fl -size-sort
.Op Fl t | -radix=format
.Op Fl -target=name
.Op Fl u | -undefined-only | -defined-only
.Op Fl V | -version
.Op Fl v
.Ar file ...
.Sh DESCRIPTION
.Nm 
utility display symbolic information in object, executable, object library
file. If no symbolic information for valid input file, no error return.
If file arguments are empty, read a.out.
.Pp
Default output format is bsd format, decimal radix, alphabetically name sort,
no-demangle.
.Pp
The symbol type list. If the symbol is lowercase, it is local. If the symbol
is uppercase, it is global.
.Bl -tag -width
.It A
absolute symbol.
.It B
bss symbol.
.It C
common symbol.
.It D
data symbol.
.It F
filename in aout, external only.
.It I
alias definition in aout.
.It N
debugging symbol.
.It T
text symbol.
.It U
undefined symbol.
.It V
weak object.
.It W
weak symbol.
warning refs in aout, internal only.
.It ?
None of the above.
.El
.Pp
Options:
.Bl -tag -width ".Fl d Ar argument"
.It Fl A | -print-file-name
Write the full pathname or library name of an object on each line
.It Fl a | -debug-syms
Display all symbols include debugger-only symbols
.It Fl B
Display in bsd format style, same as --format=bsd
.It Fl C | -demangle=style
Decode low-level symbol names. Supported style are 'auto'(default), 'gnu-v3'
.It Fl -no-demangle
Don't demangle low-level symbol names(default)
.It Fl D | -dynamic
Display only dynamic symbols
.It Fl e
Display only global and static symbol. Same as -g
.It Fl f
Produce full output. Same as default output
.It Fl -format=format
Display output in specific format. Supported format are 'bsd'(default), 'posix'
.It Fl g
Display only global symbol information
.It Fl h | -help
Show help message.
.It Fl l | -line-numbers
Display filename and line number using debugging information
.It Fl n | -numeric-sort
Sort symbols numerically by value
.It Fl o
Write numeric values in octal. Same as -t o
.It Fl P
Write information in a portable output format. Same as --format=posix
.It Fl r | -reverse-sort
Reverse the order of the sort
.It Fl S | -print-size
Print size instead value
.It Fl s | -print-armap
Include the index of archive members
.It Fl -size-sort
Sort symbols by size
.It Fl t Ar format
Write each numric value in the specified format. 'd' for decimal, 'o' for
octal, and 'x' for hexadecimal
.It Fl -target=name
Specify an object code format. Supported target 'elf', 'aout'.
.It Fl u | -undefined-only
Display only undefined symbols
.It Fl -defined-only
Display only defined symbols
.It Fl V | -version
Show the version number
.It Fl v
Sort output by value insted of alphabetically.
.It Fl x
Write numeric values in hexadecimal. Same as -t x
.El
.Sh EXIT STATUS
.Ex -std
.Sh SEE ALSO
.Xr ar 1
.Xr objdump 1
.Xr ranlib 1
.Sh AUTHORS
This manual page was written by
.An Hyogeol Lee Aq hyogeollee@gmail.com .
