.\" Copyright (c) 2007 S.Sam Arun Raj
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\" $FreeBSD$
.\"
.Dd April 15, 2007
.Dt STRINGS 1
.Os
.Sh NAME
.Nm strings
.Nd "print the strings of printable characters in files"
.Sh SYNOPSIS
.Nm
.Op Fl afho
.Op Fl e Ar encoding
.Op Fl n Ar number 
.Op Fl t Ar radix
.Op Ar
.Sh DESCRIPTION
Fo each 
.Ar file 
given, the
.Nm
utility prints any contiguous seqeunce of printable 
characters of atleast 'n' characters long (the default is 4 characters)
followed by an unprintable character.
.Nm
only scans the initialized and loaded sections of ELF objects; for other
file types, the entire file is scanned.
The
.Nm
utility is mainly useful for determining the contents of non-text files.
.Pp
If no file name is specified in the input, standard input is read from.
.Pp
The following options are available:
.Bl -tag -width indent
.It Fl a
This option instructs
.Nm
to scan the entire file. This is useful to override the default behaviour of
scanning only initialized and loaded section of ELF objects.
.It Fl e Ar encoding
Select the character encoding to be used while searching for strings. 
The encoding depends on the single character argument which speicifes 
the encoding;
.Ar s
for single 7-bit-byte characters (ASCII, ISO 8859, etc., default).
.Ar S
for single 8-bit-byte characters.
.Ar l
for 16-bit littleendian.
.Ar b
for 16-bit bigendian.
.Ar L
for 32-bit littleendian.
.Ar B
for 32-bit bigendian.
.It Fl f
Print the name of the file before each string.
.It Fl t Ar radix
Print the offset from the start of the file before each string. The 
format depends on the single character argument which specifies the 
radix of the offset;
.Ar d
for decimal,
.Ar o
for octal,
.Ar x
for hexadecimal.
.It Fl n Ar number
Print the contiguous character sequence of alteast
.Ar number
characters long, instead of default 4 characters.
.It Fl o
This is same as -t o.
.It Fl h
This prints a usage summary and exits.
.El
.Sh EXIT STATUS
.Ex -std
.Sh EXAMPLES
The following are examples of typical usage
of the
.Nm
command:
.Dl ""
.Dl "$ strings /bin/ls"
.Dl "$ strings -a /bin/ln"
.Dl "$ strings -a -f -t x /bin/cat"
.Sh SEE ALSO
.Xr ar 1 ,
.Xr nm 1 ,
.Xr objdump 1 ,
.Xr ranlib ,
.Xr readelf 1
.Sh HISTORY
The first FreeBSD
.Nm
utility appeared in
.Fx v3.
It was later discontinued in
.Fx v5 ,
when i386-only a.out format was dropped in favor of ELF.
.Sh AUTHORS
.An -nosplit
The
.Nm
utility was re-written by
.An S.Sam Arun Raj Aq samarunraj@gmail.com
This manual page was written by
.An S.Sam Arun Raj Aq samarunraj@gmail.com
.Sh LIMITATIONS
Unlike the GNU
.Nm
this doesn't support multiple object file formats, only ELF using the
.Xr elf 3
and
.Xr gelf 3
API's.
